### ISSUE TITLE
Configuration degeneracy 

### ISSUE THREAD

**Issue by aronwalsh** [bjmorgan/bsym#2]
In the materials notebook example, it is not an error, but the configuration degeneracy depends on the route:

Sequential substitutions: 
[4, 4, 4, 1, 2]

Simultaneous substitutions:
[64, 64, 64, 16, 32]

The latter should be more relevant for statistical analysis / thermodynamics for materials, which should be mentioned.

**Comment by bjmorgan** [comment]
I have updated the `unique_structure_substitutions` function in `bsym.interface.pymatgen`. `Structure` objects generated now have two additional attributes:  
`number_of_equivalent_configurations` which gives the degeneracy under that substitution, and  
`full_configuration_degeneracy` which records the cumulative product of degeneracies from sequential substitutions. 

I have updated the example in the Jupyter notebook to explain the difference between these two values.

relevant commit: f8048f7d2b372e2540e87e74d363f7a4e88e705d
